version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: test_erd_plus
    ports:
      - "13336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptestpassword"]
      timeout: 20s
      retries: 10

  erd-plus:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data:/data
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=testpassword
    tty: true
    stdin_open: true

volumes:
  mysql_data:
